[package]
name = "airnope"
version = "0.0.1"
edition = "2021"

[dependencies]
acap = "0.3.0"
actix-cors = "0.7.0"
actix-web = "4.9.0"
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive"] }
colored = "2.1.0"
dirs = "5.0.1"
futures = "0.3.31"
log = "0.4.22"
moka = { version = "0.12.8", features = ["future"] }
pretty_env_logger = "0.5.0"
rayon = "1.10.0"
regex = "1.11.1"
rust-bert = { version = "0.22.0", features = ["download-libtorch"] }
serde = "1.0.215"
teloxide = { version = "0.13.0", features = ["ctrlc_handler", "webhooks-axum"] }
tokio = { version = "1.41.1", features = ["rt-multi-thread", "macros", "fs", "rt"] }
url = "2.5.3"
walkdir = "2.5.0"

[profile.release]
lto = true
